Repository Important-is-Great-Youths/QuickQuestion, pull requests merged in 2024-05, with the labels that each got.

#11 Button 컴포넌트 스토리북 구현
  package-lock.json
  package.json
  src/app/fonts/PretendardVariable.woff2
  src/app/globals.css
  src/app/layout.tsx
  src/app/page.module.css
  src/components/common/Button.module.scss
  src/components/common/Button.tsx
  src/stories/Button.stories.ts
  src/stories/Button.tsx
  src/stories/Configure.mdx
  src/stories/Header.stories.ts
  src/stories/Header.tsx
  src/stories/Page.stories.ts
  src/stories/Page.tsx
  src/stories/assets/accessibility.png
  src/stories/assets/accessibility.svg
  src/stories/assets/addon-library.png
  src/stories/assets/assets.png
  src/stories/assets/avif-test-image.avif
  src/stories/assets/context.png
  src/stories/assets/discord.svg
  src/stories/assets/docs.png
  src/stories/assets/figma-plugin.png
  src/stories/assets/github.svg
  src/stories/assets/share.png
  src/stories/assets/styling.png
  src/stories/assets/testing.png
  src/stories/assets/theming.png
  src/stories/assets/tutorials.svg
  src/stories/assets/youtube.svg
  src/stories/button.css
  src/stories/header.css
  src/stories/page.css
Labels: ✅ Test

#15 feat : input 컴포넌트 스타일 storybook 구현
  src/components/common/Input.module.scss
  src/components/common/Input.tsx
  src/stories/Input.stories.ts
Labels: ✅ Test

#16 storybook : Tags 컴포넌트 구현
  src/components/common/Tags.module.scss
  src/components/common/Tags.tsx
  src/stories/Tags.stories.ts
Labels: ✅ Test

#25 layout 구현
  src/app/layout.module.scss
  src/app/layout.tsx
  src/app/page.module.scss
  src/app/page.tsx
  src/app/questionlist/page.tsx
  src/app/questionlist/questionlist.module.scss
Labels: 🎨 UI

#29 폰트 추가
  src/app/fonts/YangjinV0.9.ttf
  src/app/layout.tsx
  src/app/page.tsx
Labels: ⚙ Setting

#33 Header 구현
  src/components/common/Header/Header.module.scss
  src/components/common/Header/Header.tsx
  src/components/common/Tags/Tags.module.scss
  src/components/common/Tags/Tags.tsx
  src/stories/Header.stories.ts
  src/stories/Input.stories.ts
  src/stories/Tags.stories.ts
Labels: ✅ Test

#32 테마 버튼 구현
  package-lock.json
  package.json
  src/app/layout.tsx
  src/app/page.module.scss
  src/app/page.tsx
  src/app/questiondetail/page.tsx
  src/app/questiondetail/questiondetail.module.scss
  src/components/common/Button/ThemeButton.module.scss
  src/components/common/Button/ThemeButton.tsx
  src/styles/mixins/_text-style.scss
  src/styles/variables/_typography.scss
Labels: ✨ Feature, 🎨 UI

#35 Alert Modal 컴포넌트 구현
  .storybook/preview.ts
  src/components/common/AlertModal/AlertModal.module.scss
  src/components/common/AlertModal/AlertModal.tsx
  src/stories/AlertModal.stories.ts
Labels: ✅ Test

#39 Card 컴포넌트 구현
  src/components/common/Card/Card.module.scss
  src/components/common/Card/Card.tsx
  src/stories/Card.stories.ts
Labels: ✅ Test

#41 axios 초기 설정 및 API 모듈화
  package-lock.json
  package.json
  src/apis/messages.ts
  src/apis/recipients.ts
  src/app/layout.tsx
  src/app/page.module.scss
  src/app/page.tsx
  src/app/providers.tsx
  src/app/questiondetail/page.tsx
  src/app/questionlist/page.tsx
  src/components/common/Button/ThemeButton.module.scss
  src/hooks/useRecipients.ts
  src/lib/axios.ts
  src/styles/base/_globals.scss
  src/types/recipients.ts
Labels: ✨ Feature

#42 Pagination UI 구현
  src/components/common/Pagination/Pagination.module.scss
  src/components/common/Pagination/Pagination.tsx
  src/components/common/Pagination/data.json
  src/stories/Pagination.stories.ts
Labels: ✅ Test

#43 질문 등록 페이지 팝업 컴포넌트 작성
  src/components/common/Button/Button.tsx
  src/components/common/Input/Input.tsx
  src/components/common/PopUp/PopUp.module.scss
  src/components/common/PopUp/PopUp.tsx
  src/stories/PopUp.stories.ts
Labels: ✅ Test

#48 PopUp에 에러 메세지 추가
  src/components/common/PopUp/PopUp.module.scss
  src/components/common/PopUp/PopUp.tsx
Labels: ✅ Test

#47 Tags에서 theme Props 제거
  src/components/common/Tags/Tags.tsx
Labels: 🛠️ Refactor, ✅ Test

#50 error message, placeholder 상수화 및 닉네임 중복 검사 구현
  src/app/page.tsx
  src/components/common/Input/Input.module.scss
  src/components/common/Input/Input.tsx
  src/constants/formMessage.ts
  src/styles/base/_reset.scss
  src/types/recipients.ts
Labels: ✨ Feature

#53 Popup 이름 변경
  src/components/common/PopUp/FindPopUp.module.scss
  src/components/common/PopUp/FindPopUp.tsx
Labels: 🛠️ Refactor, ✅ Test

#55 Input 컴포넌트 scss적용
  src/components/common/Input/Input.module.scss
  src/components/common/Input/Input.tsx
Labels: ✅ Test

#57 질문 폼 구현
  src/app/page.module.scss
  src/app/page.tsx
  src/components/common/Button/Button.module.scss
  src/components/common/Tags/Tags.module.scss
  src/components/common/Textarea/Textarea.module.scss
  src/components/common/Textarea/Textarea.tsx
  src/components/home/QuestionForm/QuestionForm.module.scss
  src/components/home/QuestionForm/QuestionForm.tsx
  src/styles/base/_reset.scss
Labels: ✨ Feature

#58 PwPopUp 작성
  src/components/common/Button/Button.module.scss
  src/components/common/PopUp/PwPopUp.module.scss
  src/components/common/PopUp/PwPopUp.tsx
  src/stories/PwPopUp.stories.ts
Labels: ✅ Test

#63 QuestionForm에 validation 설정 및 사진 첨부 기능 구현
  src/apis/recipients.ts
  src/components/common/Input/Input.tsx
  src/components/common/Tags/Tags.module.scss
  src/components/common/Textarea/Textarea.tsx
  src/components/home/QuestionForm/QuestionForm.module.scss
  src/components/home/QuestionForm/QuestionForm.tsx
  src/hooks/useRecipients.ts
  src/types/recipients.ts
Labels: ✨ Feature

#66 인기 질문 슬라이드 구현
  src/app/layout.tsx
  src/app/page.module.scss
  src/app/page.tsx
  src/components/home/CurationCardList/CurationCardList.module.scss
  src/components/home/CurationCardList/CurationCardList.tsx
  src/utils/registDragEvent.ts
Labels: ✨ Feature

#67 Tags를 react-hook-form 사용 가능한 꼴로 수정
  src/components/common/PopUp/FindPopUp.tsx
  src/components/common/PopUp/PwPopUp.tsx
  src/components/common/Tags/Tags.tsx
  src/components/common/TestModal/TestModal.tsx
  src/stories/FindPopUp.stories.ts
  src/stories/Input.stories.ts
  src/stories/TestModal.stories.ts
Labels: 🛠️ Refactor, ✅ Test

#70 Feat/reaction/59
  src/apis/recipients.ts
  src/components/common/Reaction/Reaction.module.scss
  src/components/common/Reaction/Reaction.tsx
  src/hooks/useRecipients.ts
  src/types/recipients.ts
Labels: ✨ Feature

#71 인기 질문 슬라이드 터치 기능
  public/assets/images/logo-default.png
  public/assets/images/logo-rainy-title.png
  public/assets/images/logo-rainy.png
  public/assets/images/logo-snowy-title.png
  public/assets/images/logo-snowy.png
  public/assets/images/logo-sunny-title.png
  public/assets/images/logo-sunny.png
  public/assets/images/logo.png
  src/components/common/Header/Header.tsx
  src/components/home/CurationCardList/CurationCardList.tsx
  src/components/home/QuestionForm/QuestionForm.tsx
  src/hooks/useRecipients.ts
  src/utils/registDragEvent.ts
Labels: ✨ Feature

#72 Tags value, defaultchecked, ...props 설정
  src/components/common/Tags/Tags.tsx
  src/components/common/TestModal/TestModal.tsx
Labels: 🛠️ Refactor, ✅ Test

#75 tag 컴포넌트 사용하는 코드 및 비밀번호 input type이 아이콘에 따라 변경되도록 수정
  src/app/providers.tsx
  src/components/common/Input/Input.module.scss
  src/components/common/Input/Input.tsx
  src/components/home/QuestionForm/QuestionForm.tsx
Labels: ✨ Feature, 🛠️ Refactor

#76 card 컴포넌트 수정
  src/components/common/Card/Card.module.scss
  src/components/common/Card/Card.tsx
Labels: 🛠️ Refactor

#80 해당 card에 맞는 reaction 데이터 불러오기
  src/components/common/Reaction/Reaction.tsx
  src/hooks/useRecipients.ts
Labels: 🐛 Bug, ✨ Feature

#82 인기 질문 슬라이드 버튼 및 헤더 버튼 수정
  src/app/questiondetail/[id]/page.tsx
  src/app/questiondetail/[id]/questiondetail.module.scss
  src/components/common/Card/Card.module.scss
  src/components/common/Card/Card.tsx
  src/components/common/Header/Header.tsx
  src/components/common/Reaction/Reaction.module.scss
  src/components/home/CurationCardList/CurationCardList.module.scss
  src/components/home/CurationCardList/CurationCardList.tsx
Labels: ✨ Feature

#83 Modal Provider 작성
  src/app/providers.tsx
  src/app/questionlist/page.tsx
  src/components/common/AlertModal/AlertModal.tsx
  src/components/common/ModalWrapper/ModalWrapper.module.scss
  src/components/common/ModalWrapper/ModalWrapper.tsx
  src/components/common/Tags/Tags.tsx
  src/components/common/TestModal/TestModal.tsx
  src/components/common/TestModalButton/TestModalButton.tsx
  src/components/test/ModalButton.tsx
  src/contexts/ModalProvider.tsx
  src/stories/ModalButton.stories.ts
Labels: ✨ Feature

#84 pagination/formmodal 작업 업로드
  src/components/common/FormModal/FormModal.module.scss
  src/components/common/FormModal/FormModal.tsx
  src/components/common/Pagination/Pagination.tsx
  src/components/common/Pagination/data.json
  src/components/common/Pagination/mockdata.json
Labels: 🐛 Bug, ✨ Feature

#89 ContentLayout 컴포넌트 구현
  src/components/questionDetail/ContentLayout/ContentLayout.module.scss
  src/components/questionDetail/ContentLayout/ContentLayout.tsx
  src/stories/ContentLayout.stories.ts
Labels: 🎨 UI, ✅ Test

#91 Reaction Content 컴포넌트 구현
  src/components/questionDetail/ReactionContent/ReactionContent.module.scss
  src/components/questionDetail/ReactionContent/ReactionContent.tsx
Labels: 🎨 UI

#94 QuestionListPage 구현 중
  src/app/questionlist/page.tsx
  src/app/questionlist/questionlist.module.scss
  src/components/common/FormModal/FormModal.tsx
  src/components/common/Pagination/Pagination.tsx
  src/components/common/Pagination/mockdata.json
Labels: ✨ Feature

#93 question content 컴포넌트 구현
  src/apis/recipients.ts
  src/components/questionDetail/QuestionContent/QuestionContent.module.scss
  src/components/questionDetail/QuestionContent/QuestionContent.tsx
  src/hooks/useChangeTagName.ts
  src/hooks/useDate.ts
  src/hooks/useRecipients.ts
Labels: ✨ Feature, 🎨 UI

#95 Answer Content UI 구현
  src/components/common/AnswerContent/AnswerContent.module.scss
  src/components/common/AnswerContent/AnswerContent.tsx
  src/stories/AnswerContetn.stories.ts
Labels: 🎨 UI, ✅ Test

#96 Answer Empty UI 구현 및 질문 등록 시 과정 추가
  public/assets/images/logo-default.png
  src/apis/recipients.ts
  src/app/layout.tsx
  src/app/questiondetail/[id]/page.tsx
  src/app/questiondetail/[id]/questiondetail.module.scss
  src/components/home/CurationCardList/CurationCardList.tsx
  src/components/home/QuestionForm/QuestionForm.tsx
  src/components/questionDetail/AnswerEmpty/AnswerEmpty.module.scss
  src/components/questionDetail/AnswerEmpty/AnswerEmpty.tsx
  src/hooks/useRecipients.ts
Labels: 🎨 UI

#104 Find Modal 컴포넌트 기능 구현
  src/app/questiondetail/[id]/page.tsx
  src/components/common/Header/Header.module.scss
  src/components/common/Header/Header.tsx
  src/components/common/PopUp/FindPopUp.tsx
  src/components/home/QuestionForm/QuestionForm.tsx
  src/constants/formMessage.ts
Labels: ✨ Feature

#101 Qusetion Detail 페이지 구현
  next.config.mjs
  src/app/questiondetail/[id]/page.tsx
  src/components/questionDetail/QuestionContent/QuestionContent.tsx
  src/types/recipients.ts
Labels: ✨ Feature, 🛠️ Refactor

#106 Tag name 미적용 버그 해결
  src/components/common/Tags/Tags.tsx
Labels: 🐛 Bug

#102 AnswerContent의 비밀번호 입력 팝업, 사용자에 따라서 props로 UI 변경되도록 수정하기
  src/components/common/AnswerContent/AnswerContent.module.scss
  src/components/common/AnswerContent/AnswerContent.tsx
  src/components/common/PopUp/PwPopUp.tsx
Labels: ✨ Feature, 🛠️ Refactor

#109 QuestionListPage 미답변만 보기 기능 구현
  package-lock.json
  package.json
  public/assets/images/checked.svg
  src/app/questionlist/page.tsx
  src/app/questionlist/questionlist.module.scss
  src/components/common/FormModal/FormModal.tsx
  src/components/common/NoAnswer/NoAnswer.module.scss
  src/components/common/NoAnswer/NoAnswer.tsx
  src/components/common/Pagination/Pagination.module.scss
  src/components/common/Pagination/Pagination.tsx
  src/stories/NoAnswer.stories.ts
Labels: ✨ Feature

#111 Modal 바깥쪽 클릭시 닫히는 기능 구현
  src/components/common/ModalWrapper/ModalWrapper.tsx
Labels: 🐛 Bug, 🛠️ Refactor

#113 FormModal UI 및 에러 메세지 버그 수정
  src/components/common/FormModal/FormModal.module.scss
  src/components/common/FormModal/FormModal.tsx
Labels: 🎨 UI

#114 채택 기능 및 팝업 바깥쪽 클릭 시 닫히도록 구현
  src/app/questiondetail/[id]/page.tsx
  src/components/common/AnswerContent/AnswerContent.module.scss
  src/components/common/AnswerContent/AnswerContent.tsx
  src/components/common/Button/Button.module.scss
  src/components/common/Header/Header.module.scss
  src/components/common/Header/Header.tsx
  src/components/common/Reaction/Reaction.module.scss
  src/components/common/Reaction/Reaction.tsx
  src/components/questionDetail/QuestionContent/QuestionContent.tsx
Labels: ✨ Feature

#117 AnswerContent 및 PwPopup 관련 자잘한 수정
  src/app/questiondetail/[id]/page.tsx
  src/components/common/AnswerContent/AnswerContent.module.scss
  src/components/common/AnswerContent/AnswerContent.tsx
  src/components/common/PopUp/PwPopUp.module.scss
Labels: 🐛 Bug, 🎨 UI, 🛠️ Refactor

#121 페이지네이션 스타일 수정
  public/assets/fonts/YangjinV0.9.ttf
  src/app/questiondetail/[id]/page.tsx
  src/app/questiondetail/[id]/questiondetail.module.scss
  src/app/questionlist/questionlist.module.scss
  src/components/common/Pagination/Pagination.module.scss
  src/components/common/Pagination/Pagination.tsx
  src/components/questionDetail/ContentLayout/ContentLayout.module.scss
  src/components/questionDetail/QuestionContent/QuestionContent.module.scss
  src/components/questionDetail/QuestionContent/QuestionContent.tsx
  src/components/questionDetail/ReactionContent/ReactionContent.module.scss
  src/stories/Pagination.stories.ts
  src/styles/base/_globals.scss
  src/styles/base/_reset.scss
Labels: 🎨 UI

#122 QuestionListPage 반응형 구현 및 수정
  public/assets/images/checked.svg
  src/app/questionlist/page.tsx
  src/app/questionlist/questionlist.module.scss
  src/components/common/NoAnswer/NoAnswer.module.scss
  src/components/common/NoAnswer/NoAnswer.tsx
  src/types/recipients.ts
Labels: 🎨 UI, 🛠️ Refactor

#123 AnswerContent와 PwPopup 기능 작성(미완)
  src/components/common/AlertModal/AlertModal.tsx
  src/components/common/AnswerContent/AnswerContent.module.scss
  src/components/common/AnswerContent/AnswerContent.tsx
  src/components/common/PopUp/PwPopUp.tsx
  src/components/common/Textarea/Textarea.tsx
Labels: ✨ Feature, 🛠️ Refactor

#129 form modal 구현
  src/apis/recipients.ts
  src/components/common/FormModal/FormModal.module.scss
  src/components/common/FormModal/FormModal.tsx
  src/components/questionDetail/QuestionContent/QuestionContent.tsx
  src/hooks/useRecipients.ts
  src/types/recipients.ts
Labels: ✨ Feature

#128 질문에 첨부된 사진 나오도록 구현
  next.config.mjs
  src/app/layout.module.scss
  src/app/questionlist/questionlist.module.scss
  src/components/common/NoAnswer/NoAnswer.module.scss
  src/components/common/NoAnswer/NoAnswer.tsx
  src/components/questionDetail/QuestionContent/QuestionContent.module.scss
  src/components/questionDetail/QuestionContent/QuestionContent.tsx
Labels: ✨ Feature, 🛠️ Refactor

#132 QuestionListPage 태그 필터 구현 및 title 스타일 수정
  src/app/questionlist/page.tsx
  src/app/questionlist/questionlist.module.scss
  src/components/common/Tags/Tags.tsx
Labels: ✨ Feature, 🎨 UI

#131 답변 등록 시 업데이트 안되는 현상 해결 및 답변 데이터 불러오는 함수 변경
  src/app/questiondetail/[id]/page.tsx
  src/hooks/useRecipients.ts
Labels: 🐛 Bug, ✨ Feature

#134 AnswerContent에 자잘한 수정 완료
  src/app/questiondetail/[id]/page.tsx
  src/components/common/AnswerContent/AnswerContent.tsx
  src/components/common/PopUp/PwPopUp.tsx
Labels: 🐛 Bug, 🛠️ Refactor

#139 답변 삭제에 리액트 쿼리 적용하기
  src/apis/messages.ts
  src/components/common/AnswerContent/AnswerContent.tsx
  src/hooks/useMessages.ts
Labels: ✨ Feature, 🛠️ Refactor

#140 채택 시 바로 스타일 변경되도록 수정
  src/app/layout.module.scss
  src/app/questionlist/questionlist.module.scss
  src/components/common/AnswerContent/AnswerContent.tsx
  src/components/common/Tags/Tags.tsx
  src/lib/axios.ts
  src/types/recipients.ts
Labels: 🛠️ Refactor

#144 답변 수정 관련 버그 수정
  src/components/common/AnswerContent/AnswerContent.tsx
Labels: 🐛 Bug

#146 PwPopup이 질문자 채택 outline 아래로 렌더링 되는 현상 수정
  src/components/common/AnswerContent/AnswerContent.module.scss
  src/components/common/PopUp/PwPopUp.module.scss
Labels: 🐛 Bug, 🎨 UI

#137 FormModal 이미지 에러
  src/components/common/FormModal/FormModal.tsx
  src/hooks/useRecipients.ts
Labels: 🐛 Bug

#148 중복 채택 금지 및 채택된 답변 수정, 삭제 버튼 안나오게 하기
  src/components/common/AnswerContent/AnswerContent.module.scss
  src/components/common/AnswerContent/AnswerContent.tsx
  src/components/common/FormModal/FormModal.module.scss
  src/components/common/FormModal/FormModal.tsx
  src/components/common/Textarea/Textarea.tsx
Labels: ✨ Feature, 🛠️ Refactor
