Repository Important-is-Great-Youths/QuickQuestion, pull requests merged in 2024-06, with the labels that each got.

#152 날씨 데이터 요청 및 수신 코드 작성
  .gitignore
  src/apis/getWeather.ts
  src/apis/recipients.ts
  src/app/layout.tsx
  src/app/page.tsx
  src/app/questiondetail/[id]/page.tsx
  src/app/questionlist/page.tsx
  src/components/common/Button/ThemeButton.tsx
  src/components/common/Header/Header.tsx
  src/hooks/useGetWeather.ts
  src/lib/axios.ts
Labels: ✨ Feature

#154 QuestionListpage 질문 없을 때 문구 생성
  src/app/questionlist/page.tsx
  src/app/questionlist/questionlist.module.scss
Labels: 🎨 UI

#155 사용자 위치(위도 & 경도) 데이터를 nx & ny로 변환하는 코드 작성
  src/components/common/TestComponent/TestComponent.tsx
  src/components/common/TestModalButton/TestModalButton.tsx
  src/hooks/useLonLatToXY.ts
  src/stories/TestComponent.stories.ts
Labels: ✨ Feature

#156 현재 시각 추출 및 변환
  src/hooks/useDateAndTime.ts
Labels: ✨ Feature

#161 변환된 위치값, 현재 날짜를 데이터 요청 url에 넣기 및 질문 없을 때 렌더링 될 요소 추가
  src/apis/getWeather.ts
  src/app/questionlist/page.tsx
  src/app/questionlist/questionlist.module.scss
  src/hooks/useGetWeather.ts
Labels: ✨ Feature, 🛠️ Refactor

#163 페이지네이션 초기값 1로 해서 태그값 변경 시 1로 되도록 구현
  src/app/questionlist/page.tsx
Labels: 🐛 Bug, ✨ Feature

#166 feat: use geolocation 구현
  src/app/questionlist/page.tsx
  src/hooks/useGetGeolocation.ts
Labels: 🐛 Bug, ✨ Feature

#168 alt 문구 수정
  src/components/common/AnswerContent/AnswerContent.tsx
Labels: 🛠️ Refactor

#170 동적 favicon 설정
  public/assets/images/logo-rainy.png
  public/assets/images/logo-snowy.png
  public/assets/images/logo-sunny.png
  src/app/favicon.ico
  src/hooks/useGetWeather.ts
Labels: ✨ Feature

#173 README.md 1차 작성
  README.md
Labels: ⚙ Setting

#175 useBaseDate 수정 및 스크롤 디자인 변경
  package-lock.json
  package.json
  src/components/common/FormModal/FormModal.module.scss
  src/components/common/FormModal/FormModal.tsx
  src/components/home/QuestionForm/QuestionForm.tsx
  src/hooks/useDateAndTime.ts
  src/styles/base/_reset.scss
Labels: ✨ Feature, 🛠️ Refactor

#176 README에 Feautures 추가
  README.md
Labels: ⚙ Setting
